name: Sync translations

on:
  push:
    branches:
      - 'main'

jobs:
  sync_translations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to main branch
        uses: actions/checkout@v3

      - name: Sync translations
        uses: deriv-com/translations/.github/actions/extract_and_sync_translations@main
        with:
          PROJECT_NAME: ${{ env.VITE_PROJECT_NAME }}
          CROWDIN_BRANCH_NAME: ${{ env.VITE_CROWDIN_BRANCH_NAME }}
          CROWDIN_PROJECT_ID: ${{ env.VITE_CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ env.VITE_CROWDIN_PERSONAL_TOKEN }}
          R2_ACCOUNT_ID: ${{ env.VITE_R2_ACCOUNT_ID }}
          R2_ACCESS_KEY_ID: ${{ env.VITE_R2_ACCESS_KEY_ID }}
          R2_SECRET_ACCESS_KEY: ${{ env.VITE_R2_SECRET_ACCESS_KEY }}
          R2_BUCKET_NAME: ${{ env.VITE_R2_BUCKET_NAME }}